version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: find_time
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  api:
    build:
      dockerfile: Dockerfile
      context: "./packages/server"
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./packages/server:/app
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/find_time?schema=public"

  nginx:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: nginx.Dockerfile
      context: .
    ports:
      - "8080:80"

volumes:
  postgres-data:
  pgadmin-data:
